name: MATLAB CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  BRANCH_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}

jobs:
  matlab-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/hed-standard/hed-python.git@develop

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command:  |
            addpath(genpath("hedmat")), addpath(genpath("tests")), run_tests